services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://postgres:example@postgres:5432/postgres"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    shm_size: 1g
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
