/**
 * Unit tests for HLS stream proxying via the file route handler.
 *
 * Tests verify that:
 *   1. The proxy rewrites relative and absolute URLs in HLS manifests to route
 *      through the proxy rather than pointing directly at the upstream server.
 *   2. HLS segment/sub-manifest requests (at paths generated by the rewriting)
 *      are proxied correctly.
 *
 * A real local HTTP server serves ffmpeg-generated HLS fixtures so that `fetch`
 * inside `proxyRequest` makes actual network calls – no mocking required.
 *
 * The HLS files are generated once via Docker ffmpeg and cached in
 * tests/.cache/hls/ (gitignored).  Subsequent runs reuse them.
 */

import { IncomingMessage, ServerResponse } from "node:http";
import { Socket } from "node:net";
import { join } from "node:path";
import handler from "@@/server/routes/file/[mediaId]/[fileId]/[...path]";
import { db } from "@@/server/utils/drizzle";
import { createEvent } from "h3";

// h3's sendStream stores the stream body in _data when socket is null
declare module "node:http" {
  interface ServerResponse {
    _data?: ReadableStream;
  }
}
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import {
  type FileServer,
  cacheDir,
  ensureHlsFixtures,
  startFileServer,
} from "../shared/media-fixtures";
import { enqueueMedia, runLiaseQuery, truncateAll } from "./fixtures/helpers";

// ── HLS fixture server ───────────────────────────────────────────────────────

const hlsDir = join(cacheDir, "hls");

// ── Local fixture HTTP server ────────────────────────────────────────────────

let fixtureServer: FileServer | undefined;
let hlsServerUrl: string;

// ── H3 event helpers ─────────────────────────────────────────────────────────

/**
 * Creates an H3 event whose ServerResponse has its `socket` property nulled
 * out.  h3's `sendStream` checks `!event.node.res.socket` and, when the socket
 * is absent, stores the response stream in `res._data` and returns early rather
 * than trying to pipe to an unconnected socket.  We then consume `res._data` to
 * read the proxied response body.
 */
function makeEvent(path: string, params: Record<string, string>) {
  const req = new IncomingMessage(new Socket());
  req.url = path;
  req.method = "GET";
  const res = new ServerResponse(req);

  // Shadow the prototype getter so sendStream sees no socket.
  Object.defineProperty(res, "socket", {
    get: () => null,
    configurable: true,
  });

  const event = createEvent(req, res);
  event.context.params = params;
  return event;
}

async function getResponseBody(
  event: ReturnType<typeof makeEvent>,
): Promise<string> {
  await handler(event);
  const stream = event.node.res._data;
  if (!stream) return "";
  return new Response(stream).text();
}

// ── DB helpers ───────────────────────────────────────────────────────────────

async function seedHlsMedia(url: string): Promise<number> {
  enqueueMedia([
    {
      liaseSource: "test-source",
      id: Math.random().toString(36).slice(2),
      files: [
        {
          type: "main",
          url,
          ext: "m3u8",
          video: true,
          audio: true,
          image: false,
        },
      ],
    },
  ]);
  await runLiaseQuery();
  const row = await db.query.cacheMedia.findFirst();
  if (!row) throw new Error("No media seeded");
  return row.id;
}

// ── Setup / teardown ─────────────────────────────────────────────────────────

beforeAll(async () => {
  ensureHlsFixtures();
  fixtureServer = await startFileServer(hlsDir);
  hlsServerUrl = fixtureServer.url;
}, 30_000);

afterAll(() => {
  fixtureServer?.close();
});

beforeEach(truncateAll);

// ── Tests ────────────────────────────────────────────────────────────────────

describe("HLS proxy – manifest URL rewriting", () => {
  let mediaId: number;
  let virtualFilename: string;

  beforeEach(async () => {
    mediaId = await seedHlsMedia(`${hlsServerUrl}/playlist.m3u8`);
    virtualFilename = `media-${mediaId}-main.m3u8`;
  });

  it("rewrites relative segment filenames to route through the proxy", async () => {
    const event = makeEvent(`/file/${mediaId}/main/${virtualFilename}`, {
      mediaId: String(mediaId),
      fileId: "main",
      path: virtualFilename,
    });

    const body = await getResponseBody(event);
    const segmentLines = body
      .split("\n")
      .filter((line) => line && !line.startsWith("#"));

    expect(segmentLines.length).toBeGreaterThan(0);
    for (const line of segmentLines) {
      expect(line).toMatch(new RegExp(`^/file/${mediaId}/main/`));
    }
  });

  it("does not expose the upstream server address in the rewritten manifest", async () => {
    const event = makeEvent(`/file/${mediaId}/main/${virtualFilename}`, {
      mediaId: String(mediaId),
      fileId: "main",
      path: virtualFilename,
    });

    const body = await getResponseBody(event);
    expect(body).not.toContain(hlsServerUrl);
  });

  it("leaves HLS directive comment lines unchanged", async () => {
    const event = makeEvent(`/file/${mediaId}/main/${virtualFilename}`, {
      mediaId: String(mediaId),
      fileId: "main",
      path: virtualFilename,
    });

    const body = await getResponseBody(event);
    expect(body).toContain("#EXTM3U");
    expect(body).toContain("#EXT-X-TARGETDURATION");
    expect(body).toContain("#EXT-X-ENDLIST");
  });
});

describe("HLS proxy – segment routing", () => {
  let mediaId: number;

  beforeEach(async () => {
    mediaId = await seedHlsMedia(`${hlsServerUrl}/playlist.m3u8`);
  });

  it("proxies a segment at a rewritten sub-path", async () => {
    // After the manifest is rewritten, segment URLs look like:
    //   /file/{id}/main/segment000.ts
    // The handler must proxy these through rather than rejecting them.
    const event = makeEvent(`/file/${mediaId}/main/seg0.ts`, {
      mediaId: String(mediaId),
      fileId: "main",
      path: "seg0.ts",
    });

    await expect(handler(event)).resolves.not.toThrow();
  });
});
